language: node_js
dist: bionic
cache:
  directories:
    - sysconfcpus
before_install:
  - | # https://github.com/elm-lang/elm-compiler/issues/1473
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi
  - npm i
  - npm install -g elm@latest
  - elm --version
script:
  - export PATH=$(npm bin):$PATH
  - cd examples/just-crop
  - ../../sysconfcpus/bin/sysconfcpus -n 2 elm make --optimize Main.elm
  - cd ../crop-and-get-cropped-image
  - ../../sysconfcpus/bin/sysconfcpus -n 2 elm make --optimize src/Main.elm
  - cd ../..
